# Generated by Django 4.0.5 on 2023-01-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Bidder', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(error_messages={'unique': 'Already Existing'}, max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Logo_Bid_details',
            fields=[
                ('Title', models.CharField(error_messages={'unique': 'Already Existing'}, max_length=100, primary_key=True, serialize=False)),
                ('AuctionStart', models.DateTimeField()),
                ('AuctionEnd', models.DateTimeField()),
                ('StartBidAmount', models.IntegerField(default=100)),
                ('WinStatus', models.CharField(choices=[('1', 'yes'), ('0', 'no')], default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Logo_listing',
            fields=[
                ('Title', models.CharField(error_messages={'unique': 'Already Existing'}, max_length=100, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Creator', models.CharField(default='admin', max_length=200)),
                ('Status', models.CharField(choices=[('1', 'yes'), ('0', 'no')], default='0', max_length=2)),
                ('Owner', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='auction_images')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Full_Name', models.CharField(max_length=100)),
                ('username', models.CharField(error_messages={'unique': 'Already Existing'}, max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Account_type', models.CharField(max_length=10)),
            ],
        ),
    ]
